// Chapters A: scope, page graph and data flow, technical structure, scaling, layers, colour, typography, rhythm.
import { observedHtml, measuredHtml, inferredHtml, ruleHtml, data, p, t, h, sub, br, a, link, img, esc, observed, measured, inferred, rule, table, code, cssBlock, rem, chunkUrl, excerpt, interactions, ORIGIN, LANG, CDN, CMS, shotIf, pageOf, routeOf, cssText } from './lib.mjs';
const I = interactions || {};
const pages = data.pages; const desktop = Object.keys(pages).filter(k => !pages[k].mobile); const mobile = Object.keys(pages).filter(k => pages[k].mobile);
const main = pages['zh-cn_main']; const mMain = pages['m_zh-cn_main'];
const px = (remV, base = 56.25) => +(parseFloat(remV) * base).toFixed(2);
const CH = { KV: 285, CAMPS: 286, CHARACTERS: 287, NEWS: 288, NEWS_NEWS: 295, NEWS_ANNOUNCE: 296, NEWS_EVENT: 297, WORLD: 290, VIDEO: 1332, SOCIAL_FOLLOW: 292, PRIVACY: 294, TERMS: 293 };
export const chapters = [
  { slug: 'scope', title: 'Scope, evidence rules and how to read this page', html() {
    const out = [];
    out.push(p(`This handbook describes the Zenless Zone Zero official website at <strong>${esc(ORIGIN)}/${LANG}/main</strong> to a depth of one navigation step, on both of its trees: the desktop tree under /${LANG}/… and the phone tree under /m/${LANG}/… that the site itself serves to mobile user agents. ${desktop.length} desktop pages and ${mobile.length} mobile pages were captured in headless Chromium on ${esc((main.capturedAt || '').slice(0, 10))}; every number, class name, colour and file name in these chapters comes from the shipped code, from the responses the pages received, or from measurements taken in that browser.`));
    out.push(observed(`Desktop pages captured: ${desktop.map(k => pages[k].route ? pages[k].route.path + (pages[k].route.query && Object.keys(pages[k].route.query).length ? '?' + new URLSearchParams(pages[k].route.query) : '') : k).join(', ')}.`));
    out.push(observed(`Mobile pages captured (iPhone user agent, 390×844 CSS px, device pixel ratio 2): ${mobile.map(k => pages[k].route ? pages[k].route.path : k).join(', ')}.`));
    out.push(p('How to read: <strong>OBSERVED</strong> = read from shipped code or responses · <strong>MEASURED</strong> = reported by headless Chromium · <strong>INFERRED</strong> = interpretation, never a fact · <strong>RULE FOR A CHILD SITE</strong> = transferable instruction derived from the above. Where a value is given in rem, the root font-size is the one the site computes from the viewport (chapter on rendering scale); the bracketed pixel values are for a 1440 px wide desktop window and a 390 px wide phone.'));
    out.push(p(`What is not in scope: the pages behind the "更多" (more) menu that live on other hosts (充值 at sdk.hoyoverse.com/payment, 攻略 at act.hoyolab.com), the account pages at account.hoyoverse.com that open in an iframe when the user icon is clicked, and the game itself. The redemption page at /redemption is on this host but is a separate build (it loads its own bundles from act.hoyoverse.com); it is described where the nav reaches it and archived with the originals.`));
    out.push(sub('Where the evidence lives on this host'));
    out.push(table(['Folder', 'Contents'], [
      [a('capture/', '/capture/'), 'network manifest (' + data.manifest.length + ' responses), the 51 chunks of the build, the 65 stylesheets extracted from them, per-page DOM snapshots, screenshots, computed styles, hover diffs, style-mutation timelines, media logs, and the interaction measurements (interactions.json)'],
      [a('source/', '/source/'), 'beautified chunks, 1,457 split webpack modules, the module map, the Nuxt route table and the readable reconstructions of the first-party modules'],
      [a('analysis/', '/analysis/'), 'every CSS rule with its media context, colour, typography, spacing, layer and motion tables, hover states, per-component evidence files'],
      [a('archive/ and /_nuxt/', '/archive/index.json'), 'the originals: every file the pages load, every API and i18n answer, kept verbatim with digests (chapter on the originals archive)'],
    ]));
    return out.join('');
  } },
  { slug: 'routes', title: 'Page graph, routes and data flow', html() {
    const out = []; const routes = data.routes;
    out.push(p(`The site is a single-page application: one HTML shell is served for every path, and <strong>vue-router</strong> (history mode) decides which page component to mount from the route table compiled into the client bundle. The table below is the shipped route table (${routes.length} records), read from ${a('/_nuxt/be1f69b.js', chunkUrl('be1f69b'))}; each record names the webpack chunks the router downloads before mounting the page and the module id of the page component.`));
    out.push(table(['Path', 'Route name', 'Chunks loaded on demand', 'Page module'], routes.map(r => [esc(r.path), esc(r.name), r.chunks.map(c => esc(c)).join(' '), String(r.module)])));
    out.push(observed(`The :lang segment is the locale (zh-cn here; the same table serves every language). Desktop and phone are two parallel trees: /:lang/… and /m/:lang/…; the inline script in the shell head sends phone user agents to the /m/ tree before Vue starts, which is why the phone capture of /${LANG}/main landed on /m/${LANG}/main.`));
    out.push(sub('The header navigation and where each entry goes'));
    const navs = (I.header && I.header.navs) || [];
    out.push(measured(`Header entries at 1440 wide: ${navs.map(n => n.text).join(' · ')}. Clicking 角色介绍 / 影像资料 / 新闻资讯 / 设定档案 changed the route to ${(I.header && I.header.navClicks || []).map(c => c.routeAfter).join(', ')} without a document reload (performance navigation entries stayed at 1), in ${(I.header && I.header.navClicks || []).map(c => c.routeChangedAfterMs + ' ms').join(', ')} from click to route change. The logo click from /${LANG}/video returned to ${(I.header && I.header.logoClick || {}).routeAfter || '/zh-cn/main'}.`));
    if (I.header && I.header.moreHover) out.push(measured(`Hovering 更多 opens a sub-menu with ${I.header.moreHover.subItems.length} links: ${I.header.moreHover.subItems.map(s => s.text + ' → ' + s.href.replace(/\?.*$/, '')).join('; ')}.`));
    out.push(sub('Content comes from one CMS API'));
    out.push(observed(`Every list and article on the site is fetched at run time from <strong>${esc(CMS)}</strong> with three GET endpoints: /getContentList (paged lists of a channel), /getContent (one record with its neighbours when iAround=1) and /getChildTree (the sub-channels of a channel). The parameter names are the API's: iChanId, iPageSize, iPage, iInfoId, iAround, sLangKey.`));
    out.push(table(['Channel id', 'Used for', 'Request the pages made'], [
      [String(CH.KV), 'home key visual (hero slides)', 'getContentList?iChanId=285&iPageSize=1&iPage=1'],
      [String(CH.CAMPS), 'character factions (camps)', 'getContentList?iChanId=286&iPageSize=50&iPage=1'],
      [String(CH.CHARACTERS), 'characters', 'getContentList?iPageSize=200&iPage=1&iChanId=287'],
      [String(CH.NEWS), 'news, all categories', 'getContentList?iPageSize=7&iPage=1&iChanId=288 (home), ?iPageSize=9 (news index), getChildTree?iChanId=288'],
      [`${CH.NEWS_NEWS} / ${CH.NEWS_ANNOUNCE} / ${CH.NEWS_EVENT}`, 'news tabs 新闻 / 公告 / 活动', 'getContentList?iPageSize=9&iPage=n&iChanId=295|296|297'],
      [String(CH.WORLD), 'world (设定档案) entries', 'getContentList?iPageSize=10&iPage=1&iChanId=290'],
      [String(CH.VIDEO), 'videos; sub-channels 1338–1341 are the tabs', 'getContentList?iPageSize=9&iPage=1&iChanId=1332, getChildTree?iChanId=1332'],
      [String(CH.SOCIAL_FOLLOW), 'social follow links', 'declared in the constants module'],
      [`${CH.TERMS} / ${CH.PRIVACY}`, 'terms of service / privacy policy documents', 'getContentList?iPageSize=1&iPage=1&isPreview=0&iChanId=293|294'],
    ]));
    out.push(observed('A list answer is {retcode, message, data:{iTotal, list:[…]}}; each record carries sChanId[], sTitle, sIntro, sUrl, sAuthor, sContent (HTML), sExt (a JSON string of named images and fields), dtStartTime, dtEndTime, dtCreateTime, iInfoId, sTagName[], sCategoryName, sSign. /getContent adds around:{prevContent, nextContent}. The news index reported iTotal = 1535 records on 2026-10-03.'));
    out.push(excerpt('28', 'CHANNEL_ID_CONFIG', 40, { skip: 0 }));
    out.push(excerpt('1118', '/getContent"', 24, { skip: -16 }));
    out.push(sub('Everything else the pages request'));
    const hosts = {}; for (const m of data.manifest) { const hst = m.url.split('/')[2]; hosts[hst] = hosts[hst] || { n: 0, types: {} }; hosts[hst].n++; const ty = (m.type || '').split('/')[0] || '?'; hosts[hst].types[ty] = (hosts[hst].types[ty] || 0) + 1; }
    out.push(table(['Host', 'Responses', 'What it serves'], Object.entries(hosts).sort((x, y) => y[1].n - x[1].n).map(([hst, v]) => [esc(hst), String(v.n), esc({ 'fastcdn.hoyoverse.com': 'images and videos of the CMS records, i18n JSON', 'zenless.hoyoverse.com': 'the shell, the /_nuxt/ chunks, fonts and images bundled with the build', 'webstatic.hoyoverse.com': 'HoYoverse SDK scripts (account, footer, analysis), i18n JSON, SDK images, background music', 'sg-public-api-static.hoyoverse.com': 'the CMS API', 'sg-public-api.hoyoverse.com': 'ip_location (region), subscription account index', 'sg-public-data-api.hoyoverse.com': 'device fingerprint', 'passport-api-sg.hoyoverse.com': 'cookie-token verification (account SDK)', 'log-upload-os.hoyoverse.com': 'event log upload', 'minor-api-os.hoyoverse.com': 'h5 log batch', 'www.google-analytics.com': 'GA4 hits (G-4MDLY4VQB3, G-8BR44XDKVQ)', 'www.googletagmanager.com': 'gtag.js', 'apmplus.ap-southeast-1.volces.com': 'APM settings and monitor collect (aid 1000089)', 'act.hoyoverse.com': 'APM helper SDK and the redemption app bundles', 'static.cloudflareinsights.com': 'Cloudflare browser insights beacon' }[hst] || Object.entries(v.types).map(([k, n]) => `${k} ×${n}`).join(', '))])));
    out.push(observed('Internationalisation strings are not in the bundle: the mi18n loader fetches JSON dictionaries per language from webstatic.hoyoverse.com/admin/mi18n/… and fastcdn.hoyoverse.com/mi18n/… (the m… ids in the manifest); the page text, nav labels and SDK strings are read from them with $getI18nWord(key).'));
    out.push(rule('Build the child site as an SPA shell plus a content API with the same three verbs and the same record shape; keep the channel ids as configuration (the constants module shows the complete map), keep text in per-language JSON dictionaries, and keep the phone tree as separate routes rather than a responsive variant of the desktop pages.'));
    return out.join('');
  } },
  { slug: 'structure', title: 'Technical structure: Nuxt 2 shell, webpack 4 chunks, injected CSS, SDKs', html() {
    const out = []; const js = data.jsCss.js; const kinds = {}; for (const m of Object.values(data.moduleMap)) kinds[m.kind] = (kinds[m.kind] || 0) + 1;
    out.push(observed(`Stack read from the shipped code: Nuxt 2 in SPA mode (window.__NUXT__ holds only {config:{_app:{basePath:"/",assetsPath:"/_nuxt/",cdnURL:null}}}, no server-rendered state), Vue ${esc(main.vueVersion || '2.7.4')} runtime, vue-router, Vuex, vue-meta (the data-n-head attributes in the shell), webpack 4 (window.webpackJsonp chunk loading, public path "/_nuxt/"), Swiper 4.5.1 for every carousel, GSAP with ScrollTrigger for scroll-driven motion, axios behind a HoYoverse request layer, lodash, date-fns, vant and pdf.js inside the vendor bundle, and the HoYoverse SDKs loaded as separate scripts: jquery 1.11.1 (dependency of the SDK scripts), hoyoverse-account-sdk, hoyoverse-footer, analysis v2, and the APM helper.`));
    out.push(sub('The shell (one file for every route)'));
    out.push(p(`The server answers every path with the same 8 KB document: meta tags, the loading placeholder with an inline &lt;style&gt; element, the SDK scripts, the four entry scripts and the APM bootstrap. The archived copy is ${a('original/shell-response.html', '/original/shell-response.html')}; its head script order is the one below.`));
    out.push(code(['<script src="https://webstatic.hoyoverse.com/dora/base/jquery-1.11.1.js">', '<script>window.__cmpblockflag=!0</script>', '<script src="https://webstatic.hoyoverse.com/dora/biz/hoyoverse-footer/v1/footer.js" async>', '<script src="https://webstatic.hoyoverse.com/dora/biz/hoyoverse-account-sdk/main.js" crossorigin="anonymous">', '<script src="https://webstatic.hoyoverse.com/dora/biz/analysis/v2/main.js">', '<base href="/">', '<link rel="preload" href="/_nuxt/b83911d.js" as="script"> …2e4935f, be1f69b, 8c4c131', '<div id="__nuxt"><style>.zzz-loading{position:fixed;…z-index:997}…</style><div class="zzz-loading">…</div></div>', '<script>window.__NUXT__={config:{_app:{basePath:"/",assetsPath:"/_nuxt/",cdnURL:null}}}</script>', '<script src="https://act.hoyoverse.com/common/event/packages/apm-helper/index.js" crossorigin="anonymous">', '<script>window.__APM_INIT_CONFIG__={plugins:{pageview:{routeMode:"hash"},…}}</script>', '<script src="/_nuxt/b83911d.js"> <script src="/_nuxt/2e4935f.js"> <script src="/_nuxt/be1f69b.js"> <script src="/_nuxt/8c4c131.js">'].join('\n'), { max: 20 }));
    out.push(sub('The build: 51 chunks, 1,457 modules'));
    out.push(table(['Chunk', 'Bytes', 'Role', 'Routes that load it'], js.sort((x, y) => (x.kind > y.kind ? 1 : x.kind < y.kind ? -1 : y.bytes - x.bytes)).map(c => [a(c.url.split('/').pop(), c.url), String(c.bytes), esc(c.kind + (c.chunkId !== null && c.chunkId !== 'entry' ? ' #' + c.chunkId : '')), c.routes.map(esc).join(', ') || (c.kind === 'route chunk' ? '(shared by the routes above)' : 'every page')])));
    out.push(observedHtml(`Module kinds after splitting the chunks: ${Object.entries(kinds).map(([k, n]) => `${k} ${n}`).join(', ')}. The complete naming is in ${a('source/MODULE-MAP.md', '/source/MODULE-MAP.md')}; the first-party modules (pages, layout components, store, API client, plugins) are reconstructed readably under ${a('source/readable/', '/source/readable/')}.`));
    out.push(sub('CSS is shipped inside the JavaScript'));
    out.push(observedHtml(`There is no stylesheet file: ${data.cssIndex.length} css-loader modules (${Math.round(data.cssIndex.reduce((n, c) => n + c.bytes, 0) / 1024)} KB of CSS) are strings inside the chunks, and vue-style-loader appends one &lt;style&gt; element per module to the head when the module executes. The home page therefore ends with ${main.styleTags.length} &lt;style&gt; tags (${Math.round(main.styleTags.reduce((n, s) => n + s.chars, 0) / 1024)} KB); the news article page with ${pages['zh-cn_news_166535'] ? pages['zh-cn_news_166535'].styleTags.length : '—'}. ${data.cssIndex.filter(c => c.scoped).length} of the modules are Vue scoped styles (selectors carry a [data-v-…] attribute). Each extracted stylesheet is at ${a('capture/css/<module id>.css', '/capture/css/index.json')}, byte for byte what the browser receives, with the url() targets resolved the way css-loader resolves them at run time.`));
    out.push(table(['Module', 'Carried by chunk(s)', 'Bytes', 'Rules', 'First selector'], data.cssIndex.map(c => [a(String(c.moduleId), '/' + c.file), c.chunks.map(esc).join(' '), String(c.bytes), String(c.rules), esc(c.firstSelector.slice(0, 60)) + (c.scoped ? ' (scoped)' : '')])));
    out.push(sub('The Vuex store'));
    out.push(observed(`State keys read from the running store on the home page: ${Object.keys(main.vuex || {}).join(', ')}. Mutations seen in the components: setUserInfo, setBaseInfo, setLoading, setHomeSection, setNewsCates, setVideoCates, setVideoMainChanName, setCharacterCamps, muteBgm.`));
    out.push(excerpt('348', 'computed: {', 22));
    out.push(rule('Reproduce the delivery model, not only the look: an SPA shell served for every path, a runtime chunk plus two vendor bundles and one app bundle, route chunks loaded by the router, CSS injected per component, SDK scripts loaded before the app, and a loading placeholder in the shell so the first paint is not blank.'));
    return out.join('');
  } },
  { slug: 'scaling', title: 'Rendering scale: the rem adapter (100 × clientWidth ÷ design width)', html() {
    const out = [];
    out.push(observed('Every length in the stylesheets is in rem. A plugin in the app bundle (module 326) sets the root font-size from the viewport: fontSize = 100 × clientWidth ÷ designWidth, with the design width 2560 for the desktop tree and 750 for the phone tree. On desktop the client width is clamped to [1440, 2560] before the division (minScaleWidth 1440, maxFillWidth 2560), so a window narrower than 1440 px keeps the 1440 layout and scrolls horizontally rather than shrinking; on phones the height (designHeight 1334) is used in landscape. The plugin also adds the class pc or mo to <html>, adds hairlines when the device pixel ratio is at least 2, and only then sets #__nuxt visible.'));
    out.push(excerpt('326', 'clientWidth', 14, { skip: -4 }));
    if (I.rootFontSize) out.push(table(['Viewport', 'clientWidth', 'Measured html font-size', '100 × width ÷ 2560', 'Clamped to 1440?'], I.rootFontSize.map(r => [esc(r.viewport), String(r.clientWidth), esc(r.fontSize), esc(r.formula), r.clientWidth < 1440 ? 'yes → 56.25px' : 'no'])));
    if (I.rootFontSizeMobile) out.push(table(['Phone viewport', 'clientWidth', 'Measured html font-size', '100 × width ÷ 750'], I.rootFontSizeMobile.map(r => [esc(r.viewport), String(r.clientWidth), esc(r.fontSize), esc(r.formula750)])));
    out.push(measured(`So 1rem = 56.25px at 1440 wide, 75px at 1920, 100px at 2560 (the design canvas); 1rem = 52px on a 390 px phone. The design files were drawn at 2560 × 1440 (desktop) and 750 × 1334 (phone): a value of .46rem in the CSS is 46 px in the design and ${px('.46rem')} px on a 1440 window.`));
    out.push(table(['CSS value', 'Design px (2560)', 'At 1440 wide', 'At 1920 wide', 'Phone (390)'], ['.16rem', '.2rem', '.24rem', '.3rem', '.46rem', '1rem', '3.4rem', '12.8rem', '19.2rem'].map(v => [v, String(parseFloat(v) * 100), String(px(v)), String(px(v, 75)), String(px(v, 52))])));
    out.push(observed('The base stylesheet still declares html{font-size:14px} (module 202, the vendor reset); the inline style the plugin writes on <html> overrides it on every page load and on every resize and pageshow event.'));
    out.push(rule('Use the same adapter: author in rem against a 2560-wide (desktop) and 750-wide (phone) canvas, set html font-size = 100 × clientWidth ÷ designWidth on load, resize and pageshow, clamp the desktop width to [1440, 2560], and hide the app root until the first value is written.'));
    return out.join('');
  } },
  { slug: 'layers', title: 'Layer stack and hit testing', html() {
    const out = []; const layers = data.layers.map(l => ({ ...l, z: Number(l.zIndex) })).filter(l => !isNaN(l.z)).sort((x, y) => y.z - x.z);
    out.push(observed(`${data.layers.length} rules set a z-index. The stack, highest first (vendor and SDK layers included because they sit above the site):`));
    const seen = new Set(); const rows = []; for (const l of layers) { const k = l.selector + '|' + l.z; if (seen.has(k)) continue; seen.add(k); rows.push([String(l.z), esc(l.selector.slice(0, 70)), esc(l.position || ''), esc(l.component || ''), esc(l.source.replace(/^\/_nuxt\//, ''))]); if (rows.length >= 60) break; }
    out.push(table(['z-index', 'Selector', 'Position', 'Component', 'Source'], rows));
    out.push(measured(`On the home page at 1440 × 900 the fixed header is 1440 × 56 px (1rem high) at the top, the sidebar pager sits fixed at the right edge (${main.computed['sidebar'] ? esc(main.computed['sidebar'].width + ' × ' + main.computed['sidebar'].height) : '46 × 201 px'}), and the sections scroll beneath them; the loading overlay (.zzz-loading in the shell, then the Vue .loading component) covers the viewport at z-index 997 until the page component has mounted.`));
    out.push(inferred('The order is: content (auto) → sticky/fixed page chrome (header 99, sidebar 99, backTop) → SDK overlays (account popup, cookie tips, toast) → nuxt-progress 999999 → the user-model loading overlay at 2147483646/7, which is the request layer\'s own blocking spinner.'));
    return out.join('');
  } },
  { slug: 'colour', title: 'Colour tokens and where each one is used', html() {
    const out = []; const colors = data.colors;
    out.push(observed(`${colors.length} distinct colour literals occur in the stylesheets. The site\'s own palette is small: ink #222122 and near-blacks (#000, #111, #333), the signal yellow-green #d8fa00 (sidebar active number, borders, highlights) and its button variant #c6e800, warm yellow #ffde00, light greys #e8e8e8 / #efefef / #d6d6d6 for panels and page background, white. Most of the remaining literals are HoYoverse SDK tokens (the --global-color-* and --brand-* custom properties of the subscription/CRM widget).`));
    out.push(table(['Colour', 'Occurrences', 'Properties', 'Components', 'Example'], colors.slice(0, 40).map(c => [`<span style="color: ${esc(c.value)};">■</span> ${esc(c.value)}`, String(c.count), esc(Object.keys(c.properties).slice(0, 3).join(', ')), esc(Object.keys(c.components).slice(0, 4).join(', ')), esc((c.examples[0] || {}).selector || '').slice(0, 50)])));
    const vars = data.cssRules.rules.filter(r => /^:root/.test(r.selector)).flatMap(r => Object.entries(r.declarations)).filter(([k]) => k.startsWith('--')).slice(0, 40);
    if (vars.length) out.push(observed(`CSS custom properties declared on :root (the hyv design tokens shipped with the CRM widget, module 1056): ${vars.map(([k, v]) => k + ': ' + v).join('; ')}${vars.length >= 40 ? ' …' : ''}.`));
    out.push(measured(`Page background measured on the home page body: ${esc((main.computed['home'] || {})['background-color'] || 'see computed styles')}; header text colour ${esc((main.computed['nav-content'] || {}).color || '')}; sidebar active number ${esc((main.computed['sidebar__pagers-num--active'] || {}).color || '#d8fa00')}.`));
    out.push(rule('Keep four roles: ink (#222122) on light grey (#e8e8e8–#efefef) for reading surfaces, black panels (#000/#111/#222122) for the hero and the header, the yellow-green #d8fa00 only as the accent (active state, borders, highlights) and #c6e800 for hover on filled buttons, white for text on dark.'));
    return out.join('');
  } },
  { slug: 'typography', title: 'Typography: faces, roles, sizes', html() {
    const out = []; const ty = data.typography; const fonts = data.fonts.fonts;
    out.push(observed(`${fonts.length} @font-face declarations ship in the app bundle (modules 685 and 703 are the same font set for the desktop and the phone layouts). The faces are keyed by language: "en impact" and "en inpin" for Chinese/English display and body text, "ko scd" (S-Core Dream 9) for Korean, "ja rog" (Ro G San Serif) for Japanese, "tw cloud" for Traditional Chinese, plus the Kanit family from fastcdn for Thai, TTHovesProCompactBold, Mont-Heavy (inlined as a data: URI), and the icomoon icon font (inlined as a data: URI).`));
    out.push(table(['font-family', 'Files', 'Weight', 'Declared in'], fonts.map(f => [esc(f.family), f.sources.map(s => s.url.startsWith('data:') ? 'data: URI (' + (s.url.split(';')[0].slice(5)) + ')' : a(s.url.split('/').pop().slice(0, 50), s.url)).join('<br>'), esc(f.weight || 'normal'), esc(f.stylesheet.replace('.css', ''))])));
    out.push(observed(`The body font stack on the home page as computed: ${esc(main.bodyFont || '')}. Text set in the key visual, section titles and numbers uses the classes font-num, font-mont-heavy and font-hongmeng; the mi18n loader exposes the language font as the custom property --mi18n-font-css, which the component rules combine with the display face ("en impact", var(--mi18n-font-css) !important).`));
    out.push(sub('Sizes'));
    out.push(table(['font-size', 'Rules', 'Design px', 'At 1440 wide', 'Phone 390'], ty.sizes.slice(0, 18).map(([v, n]) => [esc(v), String(n), /rem/.test(v) ? String(parseFloat(v) * 100) : '—', /rem/.test(v) ? String(px(v)) : esc(v), /rem/.test(v) ? String(px(v, 52)) : esc(v)])));
    out.push(observed(`Line-heights used: ${ty.lineHeights.slice(0, 8).map(([v, n]) => `${v} (${n})`).join(', ')}. Letter-spacings: ${ty.letterSpacings.slice(0, 6).map(([v, n]) => `${v} (${n})`).join(', ')}.`));
    const roles = [['News article title', '.news-detail__title', '.46rem / 800 / 1.3'], ['News article body', '.news-detail__content', '.2rem / 1.5'], ['Article date and breadcrumb bar', '.news-detail__info', '.24rem on #222122'], ['Section numbers (01–06)', '.section-nav-num', 'see section chapter'], ['Character name', '.character-info-name', 'display face'], ['Nav labels', '.nav-content', 'see header chapter']];
    out.push(table(['Role', 'Selector', 'Size / weight / line-height'], roles.map(r => r.map(esc))));
    out.push(cssBlock(ty.rules.filter(r => r.family && !/van-|hyv-|textLayer|annotation/.test(r.selector)).slice(0, 30).map(r => ({ selector: r.selector, media: r.media, declarations: Object.fromEntries(Object.entries({ 'font-family': r.family, 'font-size': r.size, 'font-weight': r.weight, 'line-height': r.lineHeight, 'letter-spacing': r.letterSpacing }).filter(([, v]) => v)) })), { max: 32 }));
    out.push(rule('Load the display face per language and fall back to the language font variable; keep the scale in rem on the 2560 canvas (.16/.18/.2/.22/.24/.28/.3/.32/.42/.46rem are the steps that recur) and keep reading text at line-height 1.5 and headings at 1 to 1.3.'));
    return out.join('');
  } },
  { slug: 'rhythm', title: 'Columns, spacing scale and section rhythm', html() {
    const out = []; const sp = data.spacing;
    const secs = (main.sections || []).filter(s => /section-/.test(s.cls));
    out.push(measured(`At 1440 × 900 the desktop content column is 1080 px wide (19.2rem) centred in the 1440 window: the header inner wrapper, every home section and the footer social bar share it. The home sections stack to ${main.scrollHeight} px: ${secs.map(s => `${s.cls.replace('section section-', '')} ${Math.round(s.rect.height)} px`).join(', ')}; header 56 px, footer 424 px. The news article column is 12.8rem (${px('12.8rem')} px at 1440) with 2.6rem padding above.`));
    out.push(observed(`Spacing values that recur in the stylesheets: ${sp.slice(0, 24).map(([v, n]) => `${v} (${n})`).join('; ')}.`));
    out.push(table(['Declaration', 'Rules', 'At 1440 wide'], sp.slice(0, 30).map(([v, n]) => [esc(v), String(n), esc(v.replace(/(\d*\.?\d+)rem/g, (m, r) => px(r + 'rem') + 'px'))])));
    out.push(inferred('The rhythm is built on tenths of a rem (0.1rem = 10 design px): .1/.2/.4/.6/1rem margins between blocks, .14/.26rem gutters inside controls; sections on the home page are not equal in height but each is a full composition that the sidebar pager scrolls to as a unit.'));
    out.push(rule('Keep a 1080-px-wide (19.2rem) centred column for desktop chrome and lists, a 12.8rem reading column for articles, and spacing in multiples of .1rem.'));
    return out.join('');
  } },
];
