// Chapters F: the interactions measured live (one table per scenario) and the originals archive + mirror on this host.
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { observedHtml, measuredHtml, inferredHtml, ruleHtml, root, data, p, t, h, sub, br, a, esc, observed, measured, inferred, rule, table, code, shotIf, interactions, SITE_URL, CMS } from './lib.mjs';
const I = interactions || {};
const J = f => existsSync(join(root, f)) ? JSON.parse(readFileSync(join(root, f), 'utf8')) : null;
const human = n => n > 1048576 ? (n / 1048576).toFixed(1) + ' MB' : n > 1024 ? (n / 1024).toFixed(0) + ' KB' : n + ' B';
const js = v => esc(typeof v === 'string' ? v : JSON.stringify(v));
export const chapters = [
  { slug: 'interactions', title: 'Interactions measured live: clicks, hovers, scroll, keyboard, resize, real-time calculation', html() {
    const out = [];
    out.push(p(`Everything in this chapter was driven in headless Chromium by ${a('tools/capture-interactions.mjs', '/tools/capture-interactions.mjs')} on ${esc((I.startedAt || '').slice(0, 10))} and recorded in ${a('capture/interactions.json', '/capture/interactions.json')}. Each row is a real event sent to the live page and the state read back afterwards (route, store, Swiper indexes, computed styles, inline-style mutations, media calls). Where an event produced no change in headless Chromium the row says so; nothing is inferred from the code alone.`));
    out.push(sub('A. Root font-size (the rem canvas) per viewport'));
    out.push(table(['Viewport', 'Measured', 'Formula', 'Match'], (I.rootFontSize || []).map(r => [esc(r.viewport), esc(r.fontSize), esc(r.formula) + (r.clientWidth < 1440 ? ' (clamped to 1440)' : ''), r.match || r.clientWidth < 1440 ? 'yes' : 'no'])));
    out.push(table(['Phone viewport', 'Measured', '100 × width ÷ 750', 'Match'], (I.rootFontSizeMobile || []).map(r => [esc(r.viewport), esc(r.fontSize), esc(r.formula750), r.match750 ? 'yes' : 'no'])));
    out.push(sub('B. Loader frames'));
    out.push(table(['t (ms)', 'Shell loader', 'Vue loader', 'Root mounted'], ((I.loader || {}).frames || []).map(f => [String(f.t), f.state.zzz ? 'visible' : '—', f.state.loading ? 'visible' : '—', f.state.root ? 'yes' : 'no'])));
    sub('C. Header');
    const H = I.header || {};
    out.push(sub('C. Header'));
    out.push(table(['Event', 'Result'], [['hover 更多', js(H.moreHover && H.moreHover.subItems.map(s => s.text + ' → ' + s.href.replace(/\?.*/, '')))], ...(H.navClicks || []).map(x => ['click ' + x.text, `route ${x.routeAfter} after ${x.routeChangedAfterMs} ms, title "${x.title}", page requests ${x.apiCalls.join(' ')}`.slice(0, 300)]), ['click logo (from /zh-cn/video)', js(H.logoClick)], ['click music toggle', `bgmMuted ${H.bgm && H.bgm.stateBefore} → ${H.bgm && H.bgm.stateAfterClick} → ${H.bgm && H.bgm.stateAfterSecondClick}; icon ${H.bgm && H.bgm.iconClass}; localStorage ${(H.bgm && H.bgm.localStorageKeys || []).join(' ')}`], ['hover share icon', js(H.shareHover && H.shareHover.panel)], ['click account icon', js(H.loginClick && (H.loginClick.popups[0] || {}).src)]].map(r => r.map(x => typeof x === 'string' ? esc(x) : x))));
    const S = I.sidebar || {};
    out.push(sub('D. Sidebar pager and scroll'));
    out.push(table(['Event', 'scrollY', 'store.homeSection', 'Active number'], [...(S.clicks || []).map(x => [`click ${String(x.index + 1).padStart(2, '0')}`, String(x.scrollY), esc(x.homeSection), String(x.active + 1)]), ...(S.scrollSweep || []).map(x => [`scrollTo(${x.scrollTo})`, String(x.scrollY), esc(x.homeSection), String(x.active + 1)]), ['click next arrow (from top)', String(S.next && S.next.scrollY), '', String(S.next && S.next.active + 1)], ['click backTop', String(S.backTop && S.backTop.scrollYAfter), '', '']]));
    const E = I.hero || {}; const C = I.homeCharacter || {}; const V = I.homeVideo || {}; const N = I.homeNews || {}; const W = I.homeWorld || {}; const F = I.homeFeature || {};
    out.push(sub('E. Home sections'));
    out.push(table(['Event', 'Result'], [['hover download block', js(E.downloadHover && E.downloadHover.transform)], ['click play (hero)', js(E.playClick && { dialog: E.playClick.dialog.map(d => d.cls), video: E.playClick.video, bodyOverflow: E.playClick.bodyOverflow, close: E.playClick.closeButton, afterClose: E.playClick.dialogAfterClose })], ['click character nav item 6', js(C.navClick && { list: C.navClick.listSwiper, nameBefore: C.nameBefore, nameAfter: C.navClick.nameAfter })], ['click character next arrow', js(C.nextClick)], ['click 查看更多 (character)', js(C.moreClick)], ['click video nav item 4', js(V.navClick)], ['click video play icon', js(V.playClick)], ['news banner swiper at rest', js(N.bannerSwiper)], ['click news bullet 3', js(N.bulletClick)], ['news summary animation', js(N.summaryAnimation)], ['click world next', js(W.nextClick)], ['click feature next', js(F.nextClick)], ['click concept video play', js(F.conceptPlay)]].map(r => [esc(r[0]), r[1]])));
    const Ch = I.character || {};
    out.push(sub('F. Character page'));
    out.push(table(['Event', 'Result'], [['at rest', js({ route: Ch.route, chaSwiper: Ch.chaSwiper, pagination: Ch.pagination, campSwiper: Ch.campSwiper, name: Ch.name })], ['click pagination item 2', js(Ch.paginationClick && { chaSwiper: Ch.paginationClick.chaSwiper, name: Ch.paginationClick.name })], ['click voice button', js(Ch.voiceClick && { btnClass: Ch.voiceClick.btnClass, playerName: Ch.voiceClick.playerName, timeline: Ch.voiceClick.timeline.slice(0, 1) })], ['click language switcher', js(Ch.langSwitch && Ch.langSwitch.after)], ['click faction 4', js(Ch.campClick && { campText: Ch.campClick.campText, route: Ch.campClick.route, name: Ch.campClick.name })], ['click 更多阵营', js(Ch.expandClick)], ['press ArrowRight', js(Ch.keyboard)]].map(r => [esc(r[0]), r[1]])));
    const Vi = I.video || {}; const Ne = I.news || {}; const Wo = I.world || {}; const Fo = I.footer || {}; const Mo = I.mobile || {};
    out.push(sub('G. Video, news, article, world, footer, phone'));
    out.push(table(['Event', 'Result'], [['video: click tab 版本PV', js(Vi.tabClick)], ['video: click pager 2', js(Vi.pagerClick)], ['video: click first item', js(Vi.itemClick)], ['news: click tab 公告', js(Ne.tabClick)], ['news: click next page', js(Ne.nextPage)], ['news: click first banner', js(Ne.itemClick && { routeAfter: Ne.itemClick.routeAfter, title: Ne.itemClick.title, apiCalls: Ne.itemClick.apiCalls, fullReload: Ne.itemClick.fullReload })], ['article: click 返回', js(Ne.backClick)], ['world: at rest', js({ swiper: Wo.swiper, slides: Wo.slides && Wo.slides.slice(0, 3), slideAnimation: Wo.slideAnimation })], ['world: click next', js(Wo.nextClick && Wo.nextClick.swiper)], ['world: hover active slide', js(Wo.hover)], ['world: click active slide', js(Wo.slideClick && { routeAfter: Wo.slideClick.routeAfter, apiCalls: Wo.slideClick.apiCalls, detail: Wo.slideClick.detail })], ['footer: hover YouTube icon', js(Fo.socialHover)], ['footer: hover copy button', js(Fo.copyHover)], ['footer: click locale selector', js(Fo.localeClick)], ['phone: tap menu button', js(Mo.menuClick && { button: Mo.menuClick.button, items: Mo.menuClick.items, bodyOverflow: Mo.menuClick.bodyOverflow })], ['phone: scroll to 900', js(Mo.scrolled)]].map(r => [esc(r[0]), r[1]])));
    for (const f of ['header-login', 'hero-download-hover', 'hero-video-dialog', 'home-character-after-nav', 'character-camp', 'video-dialog', 'world-detail', 'footer-locale', 'mobile-menu']) out.push(shotIf(`capture/interactions/${f}.png`, f.replace(/-/g, ' ')));
    if (I.errors && Object.keys(I.errors).length) out.push(measured(`Steps that failed: ${esc(JSON.stringify(I.errors).slice(0, 300))}.`));
    return out.join('');
  } },
  { slug: 'originals', title: 'Originals archive and self-contained mirror: the real files, data and pages on this host', html() {
    const idx = J('archive/index.json'); const mi = J('mirror/index.json'); const vm = J('verification/mirror-report.json');
    if (!idx) return p('<strong>archive/index.json is missing — run tools/archive-originals.mjs then tools/build-mirror.mjs.</strong>');
    const files = idx.files.filter(f => f.file); const byType = {}; for (const f of files) { const k = (f.file.match(/\.([a-z0-9]+)$/i) || [])[1] || '?'; byType[k] = byType[k] || { n: 0, b: 0 }; byType[k].n++; byType[k].b += f.bytes || 0; }
    const out = [];
    out.push(t('Everything the chapters describe can be opened in its original form on this host. The archive holds, verbatim and with SHA-256 digests, every file the depth-1 pages load (desktop and phone trees), every answer the CMS API gave the pages plus every list page and record those lists name, and the SDK scripts; the mirror serves the original application from those files. Together they close the gaps a document alone cannot: the backend answers, the media, the compiled source and the parts a headless capture could not render are here as files, not descriptions.'));
    out.push(sub('A. What is archived'));
    out.push(observedHtml(`Archived on ${idx.summary.archivedAt.slice(0, 10)}: ${idx.summary.files} files (${human(idx.summary.bytes)}), ${idx.summary.api} CMS answers covering ${idx.summary.newsRecords} news records and ${idx.summary.worldRecords} world entries; ${idx.summary.mediaArchived} of the ${idx.summary.mediaUrls} media files named by the archived records are included and ${idx.summary.mediaSkipped} were left on the CDN by the size budget. The site's own build files live at ${a('/_nuxt/', '/_nuxt/b83911d.js')} under their original names (chunks, fonts, images), every other host under ${a('archive/files/<host>/…', '/archive/index.json')}; each entry in archive/index.json carries its URL, size and SHA-256.`));
    out.push(table(['Kind', 'Files', 'Bytes'], Object.entries(byType).sort((x, y) => y[1].b - x[1].b).slice(0, 14).map(([k, v]) => [esc(k), String(v.n), human(v.b)])));
    out.push(sub('B. The backend, as the pages saw it'));
    out.push(observedHtml(`The CMS answers are under ${a('archive/api/', '/archive/api/index.json')}, keyed by host + path + query with the parameters sorted, so the adapter can answer the client's own parameter order. ${idx.api.filter(x => /getContentList/.test(x.key)).length} list pages, ${idx.api.filter(x => /getContent\?/.test(x.key)).length} records, ${idx.api.filter(x => /getChildTree/.test(x.key)).length} channel trees. The API refuses cross-origin browsers (no Access-Control-Allow-Origin for other origins), so a static host must answer these itself — the mirror does.`));
    out.push(table(['Request (canonical key)', 'Status', 'Bytes', 'Archived answer'], idx.api.slice(0, 30).map(x => [esc(x.key.replace(/^.*app\/[0-9a-f]+\//, '…/')), String(x.status), String(x.bytes), a(x.file.replace('archive/api/', ''), '/' + x.file)]).concat(idx.api.length > 30 ? [[`… ${idx.api.length - 30} more in archive/api/index.json`, '', '', a('index', '/archive/api/index.json')]] : [])));
    out.push(inferred('What cannot be archived: the per-session answers of the SDK services (ip_location, device fingerprint, cookie-token verification, subscription state, event and APM logging). The mirror lets those calls go to their hosts, where the browser blocks them for a foreign origin exactly as on the local mirror; a child site replaces them with its own consent, login and analytics.'));
    out.push(sub('C. The mirror'));
    out.push(observedHtml(`The mirror is the archived shell served at every route of both trees (${mi ? mi.routes : '—'} pages: the five sections, the company documents, ${mi ? mi.newsIds.length : '—'} archived articles and ${mi ? mi.worldIds.length : '—'} world entries, plus 404.html so the SPA router answers any other path), with two changes made only in the document head: the CDN references in the shell point at the archive, and one adapter script (${a('mirror/adapter.js', '/mirror/adapter.js')}) answers the CMS API from the archive, serves i18n JSON and archived media from this host, and lets anything not archived reach its original URL. ${mi ? mi.apiCopies : '—'} CMS answers and ${mi ? mi.fileCopies : '—'} SDK files are served from rewritten copies under ${a('mirror/', '/mirror/index.json')} (media URLs pointed at the archive); the originals stay untouched. Routes: ${['/zh-cn/main', '/zh-cn/character', '/zh-cn/video', '/zh-cn/news', '/zh-cn/world', '/zh-cn/company/privacy', '/zh-cn/company/terms', '/m/zh-cn/main'].map(r => a(r, r)).join(', ')}.`));
    if (vm) out.push(measured(`tools/verify-mirror.mjs loaded the mirror from a plain static server: ${vm.results.filter(r => r.ok).length} of ${vm.results.length} checks passed — ${vm.results.map(r => (r.ok ? '✓ ' : '✗ ') + r.name).join('; ')}.`));
    out.push(code(`// mirror adapter, excerpt — mirror/adapter.js (built by tools/build-mirror.mjs)
const canonical = u => { const x = new URL(u, location.href); const q = [...x.searchParams.entries()].sort(…).map(([k, v]) => k + '=' + v).join('&'); return x.host + x.pathname + (q ? '?' + q : ''); };
const answer = u => { const k = canonical(u); for (const [re, file] of Object.entries(OVERRIDE)) if (new RegExp(re).test(k)) return file; return API[k] || null; };
XMLHttpRequest.prototype.open = function (m, u, ...r) { if (m === 'GET') { const a = answer(u); if (a) u = location.origin + a; else { const l = localFile(u); if (l) u = l; } } return open.call(this, m, u, ...r); };
// this handbook page: window.__MIRROR_OVERRIDE = { 'getContent\\\\?.*iInfoId=7013': '/handbook/handbook-content.json' }`, { max: 12 }));
    out.push(sub('D. What this changes for a child site'));
    out.push(rule('Build the backend to answer the archived requests in the archived shapes (archive/api/index.json is the contract), serve media from your own CDN with the same record fields, keep the SDK calls behind your own consent and login, and use the mirror as the reference rendering: open a mirrored page and a child page side by side at 1440 × 900 and at 390 × 844 and compare.'));
    out.push(inferred('With the archive and the mirror on the same host as this handbook, the only things a reader cannot take from here are HoYoverse\'s live services and the rights to the material: everything that can be a file is a file.'));
    return out.join('');
  } },
];
