// Chapters E: cross-cutting inventories — controls, hover states, motion, audio, imagery, responsive rules, i18n,
// JavaScript map, unrendered components, coverage matrix, the child-site blueprint.
import { observedHtml, measuredHtml, inferredHtml, ruleHtml, data, p, t, h, sub, br, a, img, esc, observed, measured, inferred, rule, table, code, cssBlock, specimen, extractAll, pageDom, shotIf, rulesFor, hoverFor, readableLink, excerpt, interactions, assetModules, mediaLogs, CDN, ORIGIN, cssText } from './lib.mjs';
const I = interactions || {};
export const chapters = [
  { slug: 'controls', title: 'Buttons and controls inventory', html() {
    const out = [];
    const rows = [['nav-content', 'header entry (div, click → router push)', 'header'], ['nav-content-sub-item', 'more-menu link', 'header'], ['m-audio-player.header__bgm', 'background music toggle', 'header'], ['share__icon', 'share panel trigger (hover)', 'header'], ['login__icon', 'account iframe trigger', 'header'], ['sidebar__pagers-num', 'section number (01–06)', 'home'], ['sidebar__nav-prev / sidebar__nav-next', 'section arrows', 'home'], ['home-kv__play', 'PV play', 'home'], ['home-kv__download', 'download block (SDK platform list)', 'home'], ['home-character__nav-item', 'character thumbnail', 'home'], ['swiper-button-prev / swiper-button-next', 'carousel arrows (Swiper)', 'home, world, feature'], ['more-btn', '查看更多 (router push)', 'home'], ['home-video__nav-item', 'video thumbnail', 'home'], ['home-video__action-icon', 'play (opens video-dialog)', 'home'], ['swiper-pagination-bullet', 'carousel bullet', 'home, news, video'], ['section__concept-video-play', 'concept video play', 'home'], ['backTop', 'back to top', 'every page'], ['me-media-icon-item', 'social link (footer SDK)', 'every page'], ['me-hover-btn.copy-btn', 'copy link', 'every page'], ['locale-selector-3HQCGC', 'language picker (footer SDK)', 'every page'], ['cha-pagination-item', 'character pagination', 'character'], ['character-voice-btn', 'voice play', 'character'], ['character-voice-lang-switcher', 'voice language', 'character'], ['side-camp-item / side-camp-expand-btn', 'faction filter / expand', 'character'], ['video-tab__item / news-tab__item', 'category tab (nuxt-link with ?category)', 'video, news'], ['mihoyo-pager-rich__button / __prev / __next', 'pager', 'video, news'], ['video-list__item', 'opens the video dialog', 'video'], ['news-list__item-banner', 'opens the article (router push)', 'news'], ['news-detail-back', '返回 BACK', 'article'], ['world__slide', 'opens the world entry', 'world'], ['m-header__menu-btn / m-header__menu-close', 'phone menu', 'phone pages']];
    out.push(table(['Class', 'Role', 'Where'], rows.map(r => r.map(esc))));
    out.push(observed(`Buttons are divs or anchors with cursor:pointer; the only <button> elements are the backTop button and the SDK forms. The pager and the tabs are the only controls that are real links (nuxt-link → <a href>), which is why they survive without JavaScript as URLs.`));
    out.push(cssBlock(rulesFor('more-btn').concat(rulesFor('back-btn'), rulesFor('backTop').slice(0, 4)), { max: 30 }));
    return out.join('');
  } },
  { slug: 'hover', title: 'Hover and active states: complete inventory', html() {
    const out = []; const rules = data.motion.hoverRules;
    out.push(observed(`${rules.length} rules in the stylesheets target :hover/:active/:focus; ${data.hover.length} of the hovered classes produced a computed-style change in headless Chromium on the captured pages (the rest are inside the SDK widgets, inside carousels that were not under the pointer, or need a touch device).`));
    out.push(table(['Hovered class', 'Pages', 'Node', 'Computed change', 'Transition'], data.hover.flatMap(hh => hh.changes.slice(0, 3).map(ch => [esc(hh.cls), esc(hh.pages.map(x => x.replace(/^zh-cn_/, '')).slice(0, 2).join(', ')), esc(ch.node.split('#')[0]), esc(Object.entries(ch.props).map(([k, v]) => `${k}: ${String(v.before).slice(0, 36)} → ${String(v.after).slice(0, 36)}`).join('; ').slice(0, 200)), esc((hh.transition || '').slice(0, 50))]))));
    out.push(sub('Every :hover rule, as shipped'));
    out.push(cssBlock(rules.filter(r => !/hyv-|van-|textLayer|annotation/.test(r.selector)), { max: 80 }));
    out.push(rule('Hover is restrained: scale 1.1–1.12 on buttons and thumbnails, colour inversion on the more-button (ink on white), opacity reveal of the active tab label, and the two-image swap on the footer copy button. Nothing else moves on hover.'));
    return out.join('');
  } },
  { slug: 'motion', title: 'Motion: keyframes, transitions and measured timelines', html() {
    const out = []; const kf = data.motion.keyframes.filter((k, i, arr) => arr.findIndex(x => x.name === k.name) === i);
    out.push(observed(`${kf.length} distinct @keyframes (${kf.map(k => k.name).join(', ')}) and ${data.motion.transitions.length} transition/animation declarations. The site's own motion is small: slideToTop (world slides), wordsLoop/wordsLoopMob (the news summary marquee), heartbeat (music icon), loadingLoop (loader), tada, the Vue transitions page-enter, slide-left/down/bottom/from-rb, zoom, scaleIn, fadeIn, namefade, logoBig/logoSmall; everything else is Swiper's slide/fade or the vendor UI (vant, pdf.js, SDK). Scroll-driven motion uses GSAP ScrollTrigger (pin-spacer/scroller classes in the vendor bundle) and the pages' own scroll listeners.`));
    out.push(table(['Keyframes', 'Steps', 'Source'], kf.map(k => [esc(k.name), esc(k.steps.map(s => `${s.at} {${Object.entries(s.declarations).map(([a, b]) => a + ': ' + b).join('; ')}}`).join(' | ').slice(0, 220)), esc(k.source.replace(/^\/_nuxt\//, ''))])));
    out.push(table(['Selector', 'transition / animation', 'Source'], data.motion.transitions.filter(tr => !/hyv-|van-|textLayer|annotation|swiper-/.test(tr.selector)).slice(0, 60).map(tr => [esc(tr.selector.slice(0, 60)), esc((tr.transition || tr.animation || '').slice(0, 80)), esc(tr.source.replace(/^\/_nuxt\//, ''))])));
    out.push(sub('Measured timelines (inline style mutations during the first seconds of each page)'));
    for (const [pgName, list] of Object.entries(data.timelines).filter(([k]) => /^(zh-cn_main|zh-cn_world|zh-cn_character|m_zh-cn_main)$/.test(k))) { out.push(measured(`${pgName}: ${list.length} animated elements; first ten: ${list.slice(0, 10).map(e => `${e.element.slice(0, 40)} ${e.first}–${e.last} ms (${Object.keys(e.props).slice(0, 3).join(', ') || e.classChanges.length + ' class changes'})`).join('; ')}.`)); }
    if (I.world && I.world.nextClick) out.push(measured(`World next-slide: ${esc(JSON.stringify(I.world.nextClick.timeline.slice(0, 2)).slice(0, 400))}.`));
    out.push(rule('Entrances are Vue <transition> classes and Swiper moves; keep durations at 0.3 s (page and slide entrances), 0.8 s for the world carousel, 20 s linear for marquees, and let GSAP ScrollTrigger drive only the scroll-pinned pieces.'));
    return out.join('');
  } },
  { slug: 'audio', title: 'Audio: background music, the voice player, mute state', html() {
    const out = []; const H = (I.header || {}).bgm || {}; const C = (I.character || {}).voiceClick || {};
    out.push(observed(`Background music is one MP3 (${esc((data.manifest.find(m => /\.mp3/.test(m.url)) || {}).url || '')}, ${Math.round(((data.manifest.find(m => /\.mp3/.test(m.url)) || {}).bytes || 0) / 1024)} KB) played by the @me/audio library (module 354) behind the m-audio-player component; the header toggle commits muteBgm and the store's bgmMuted drives the icon state (heartbeat animation while playing) and the volume computed in header-bar (0 when muted, 0.8 otherwise). The choice persists in localStorage under napSeaBgAudioOfficial. The character page has a voice player per character (character-voice-player: handleVoiceBtnClick, playMicAni/stopMicAni, updateAudioIns) with a language switcher (switchSubCv); the clips are MP3s named by the character record.`));
    out.push(measured(`Media hooks on the captured pages: ${mediaLogs().map(([pgName, l]) => `${pgName.replace(/^zh-cn_/, '')}: ${l.media.length} play() calls, ${l.audio.length} Audio/AudioContext constructions`).slice(0, 8).join('; ')}. In headless Chromium the music toggle changed store.bgmMuted ${H.stateBefore} → ${H.stateAfterClick} and localStorage ${esc((H.localStorageKeys || [])[0] || '')}; the voice button animated its --progress property (${esc(((C.timeline || [])[0] || {}).props ? C.timeline[0].props['--progress'] : 'see interactions.json')}).`));
    out.push(excerpt('348', 'handleBgmClick', 16));
    out.push(cssBlock(rulesFor('m-audio-player').concat(rulesFor('character-voice-btn'), rulesFor('character-voice-player')), { max: 30 }));
    return out.join('');
  } },
  { slug: 'imagery', title: 'Imagery: bundled assets, CMS images, data URIs, icon font', html() {
    const out = []; const assets = assetModules();
    out.push(observed(`${assets.length} asset modules are bundled with the build (url-loader): ${assets.filter(x => !x.url.startsWith('data:')).length} files under /_nuxt/img/ and /_nuxt/fonts/ (hashed names), ${assets.filter(x => x.url.startsWith('data:')).length} inlined as data: URIs. The stylesheets reference ${data.fonts.assets.length} url() files plus ${data.fonts.dataUris} data: URIs. Everything editorial — key visuals, character art, banners, world covers, video covers — comes from the CMS on fastcdn.hoyoverse.com/content-v2/nap/<record>/… and is named in the records' sExt fields.`));
    out.push(table(['Asset module', 'File', 'Chunk'], assets.filter(x => !x.url.startsWith('data:')).slice(0, 120).map(x => [String(x.id), a(x.file.split('/').pop(), x.url), esc(x.chunk)])));
    const imgs = data.manifest.filter(m => /^image\//.test(m.type || '')); const byHost = {}; for (const m of imgs) { const hst = m.url.split('/')[2]; byHost[hst] = (byHost[hst] || 0) + 1; }
    out.push(measured(`Images loaded by the captured pages: ${imgs.length} (${Object.entries(byHost).map(([k, v]) => `${k} ${v}`).join(', ')}), ${Math.round(imgs.reduce((n, m) => n + (m.bytes || 0), 0) / 1048576)} MB; the largest are character art and key visuals of 2–3 MB each.`));
    out.push(observed('The icomoon icon font (data: URI in modules 685/703) carries the UI glyphs; the social icons are inline SVG paths rendered by the footer SDK (icon-path-Twitter …).'));
    return out.join('');
  } },
  { slug: 'responsive', title: 'Responsive behaviour: two trees, four media queries, measured widths', html() {
    const out = []; const bp = data.breakpoints;
    out.push(observed(`The stylesheets contain only ${bp.mediaQueries.length} media query contexts: ${bp.mediaQueries.map(([q, n]) => `${q} (${n} rules)`).join('; ')}. Responsiveness is not done with breakpoints: the desktop tree scales every rem with the viewport (clamped at 1440) and the phone tree is a separate layout at designWidth 750; (orientation:landscape) rules adjust the phone pages when the device is turned.`));
    const main = data.pages['zh-cn_main']; out.push(measured(`Desktop home at 1920 × 1080: root font-size ${esc(main.large && main.large.rootFontSize)}, horizontal overflow ${esc(String(main.large && main.large.overflow))}, sections ${esc((main.large && main.large.sections || []).filter(s => /section-/.test(s.cls)).map(s => `${s.cls.replace('section section-', '')} ${Math.round(s.rect.height)}px`).join(', '))}.`));
    out.push(shotIf('capture/pages/zh-cn_main/desktop-1920x1080.png', 'home page at 1920 × 1080'));
    out.push(cssBlock(data.cssRules.rules.filter(r => r.media.length && !/van-|hyv-/.test(r.selector)), { max: 30 }));
    return out.join('');
  } },
  { slug: 'i18n', title: 'Internationalisation: mi18n dictionaries, language fonts, locale routing', html() {
    const out = []; const dicts = data.manifest.filter(m => /mi18n/.test(m.url)).map(m => m.url);
    out.push(observed(`The :lang segment selects the locale (middleware modules 340/584 set store.lang and initialise the mi18n loader); the dictionaries are JSON files fetched per language: ${[...new Set(dicts.map(u => u.replace(/^https?:\/\//, '')))].slice(0, 12).map(esc).join(', ')}. Components read strings with $getI18nWord(key) (base mixin, module 251); the footer SDK draws the language list; the font variable --mi18n-font-css is set on the document by the loader so the display faces fall back per language (en inpin / ko scd / ja rog / tw cloud).`));
    out.push(table(['Dictionary', 'Bytes', 'Pages'], data.manifest.filter(m => /mi18n/.test(m.url)).map(m => [a(m.url.split('/').slice(-2).join('/'), m.url), String(m.bytes), String(m.pages.length)])));
    out.push(excerpt('340', 'setLang', 18));
    out.push(rule('Keep strings out of components: a per-language dictionary fetched at start, a word() accessor, and the locale in the first path segment.'));
    return out.join('');
  } },
  { slug: 'javascript', title: 'JavaScript map: chunks, modules, readable reconstructions', html() {
    const out = []; const rd = data.readable; const site = Object.values(data.moduleMap).filter(m => /^site/.test(m.kind));
    out.push(observedHtml(`${Object.keys(data.moduleMap).length} modules: ${Object.values(data.moduleMap).filter(m => m.kind === 'vendor').length} vendor, ${site.length} first-party or HoYoverse-internal, ${Object.values(data.moduleMap).filter(m => m.kind === 'css-module').length} stylesheets, ${Object.values(data.moduleMap).filter(m => m.kind === 'asset-url').length} assets. ${rd.length} modules are reconstructed readably (scope-aware renames of the minified bindings; values, strings and control flow unchanged) under ${a('source/readable/', '/source/readable/')}.`));
    out.push(table(['Module', 'Readable file', 'What it is', 'Chunk', 'Minified bytes'], rd.sort((x, y) => Number(x.id) - Number(y.id)).map(r => [String(r.id), a(r.file, '/source/readable/' + r.file), esc(String(r.summary || '').slice(0, 160)), esc(r.chunk), String(r.bytesMinified)])));
    out.push(sub('Vendor libraries identified in the bundles'));
    const vendors = {}; for (const m of Object.values(data.moduleMap)) if (m.kind === 'vendor') vendors[m.name] = (vendors[m.name] || 0) + 1;
    out.push(table(['Library', 'Modules'], Object.entries(vendors).sort((x, y) => y[1] - x[1]).map(([n, c]) => [esc(n), String(c)])));
    out.push(excerpt('704', 'mutations', 30));
    return out.join('');
  } },
  { slug: 'unrendered', title: 'Components declared in CSS but not rendered on the captured pages', html() {
    const out = []; const list = Object.entries(data.cssComponents).filter(([k]) => !Object.values(data.pages).some(pg => pg.components.some(c => c === k || c.startsWith(k + '__') || c.startsWith(k + '--'))));
    out.push(observed(`${list.length} of ${Object.keys(data.cssComponents).length} CSS blocks never appeared in the DOM of the captured pages: SDK states (account popup, subscription dialog, toast, share tips, bridge message box), pdf.js layers, vant transitions, the gacha-detail page (lang-news-public, an iframe page), the error page and the cloud-download dialog. Their rules are in the digest and in analysis/components/.`));
    out.push(table(['Block', 'Rules', 'Stylesheet modules'], list.map(([k, v]) => [esc(k), String(v.rules), esc(v.files.map(f => f.replace('.css', '')).join(' '))])));
    return out.join('');
  } },
  { slug: 'coverage', title: 'Coverage matrix: every CSS block and where it is used in this handbook', late: true, html(cov) {
    const out = []; const emb = (cov && cov.embedded) || {};
    out.push(observed(`${Object.keys(emb).length} blocks are embedded as verbatim specimens; the others are shown by screenshot and their shipped rules (fixed/absolute chrome such as header, sidebar, loaders; SDK widgets; vendor UI).`));
    out.push(table(['Block', 'Rules', 'Renders on', 'In this handbook'], Object.keys(data.cssComponents).sort().map(k => { const on = Object.entries(data.pages).filter(([, pg]) => pg.components.some(c => c === k || c.startsWith(k + '__') || c.startsWith(k + '--'))).map(([n]) => n.replace(/^zh-cn_/, '').replace(/^m_zh-cn_/, 'm/')); return [esc(k), String(data.cssComponents[k].rules), esc(on.slice(0, 4).join(', ') + (on.length > 4 ? ` +${on.length - 4}` : '')), emb[k] ? 'specimen in ' + esc(emb[k].map(s => '#' + s).join(', ')) : (on.length ? 'screenshot + CSS' : 'CSS only')]; })));
    return out.join('');
  } },
  { slug: 'blueprint', title: 'Build a child site: the transferable rules', html() {
    const out = [];
    const rules = ['Delivery: an SPA shell served for every path (with a static loader inside it), one webpack runtime, two vendor bundles, one app bundle, route chunks on demand, CSS injected per component, SDK scripts loaded before the app.', 'Scale: author in rem on a 2560-wide desktop canvas and a 750-wide phone canvas; html font-size = 100 × clientWidth ÷ designWidth, clamped to [1440, 2560] on desktop; hide the root until the first value is set.', 'Trees: a desktop route tree and a phone route tree with the same names (m- prefix), chosen by user agent in the shell, sharing the store, the API client and the dictionaries.', 'Data: one content API with getContentList / getContent / getChildTree, channel ids as configuration, records with sTitle / sIntro / sContent (HTML) / sExt (JSON of named images) / dates / iInfoId; lists page at 7, 9, 10, 50 or 200 as the component needs.', 'Chrome: a fixed 1rem header with a 19.2rem wrapper (logo, five nav entries, more-menu, download, music, share, account); a fixed sidebar pager on the home page; a three-part footer (own social bar + back-to-top, subscription SDK, corporate footer SDK with the language picker).', 'Home: six full compositions (KV + download, characters, videos, news, world, feature) each built from one or two Swiper instances (fade for the stage, slidesPerView auto for strips, loop for banners), a sidebar that both drives and follows the scroll.', 'Inner pages: fade stage + pagination + voice player + faction rail (character); latest slider + tabs (?category) + 9-per-page grid + pager (video and news); a 12.8rem reading column with a back control and an info bar (article); a looped slide deck with slideToTop entrances (world); a document template with a pdf viewer fallback (company).', 'Tokens: ink #222122 on #e8e8e8/#efefef, black panels, accent #d8fa00 (hover #c6e800), white on dark; display faces per language with a language font variable; sizes .16–.46rem; spacing in tenths of a rem; z-index 99 for page chrome, SDK overlays above.', 'Motion: 0.3 s entrances (Vue transitions), Swiper 300 ms slides, 800 ms world slides, 20 s marquee, 0.5 s loader loop; hover = scale 1.1–1.12 or colour inversion only.', 'Audio: one looping background track behind a persisted mute toggle; per-record voice clips with a progress ring.', 'Services you must replace: the content API (host it yourself with the same shapes), the account SDK, the subscription widget, analytics and APM, the download platform list; everything else is a file and is archived on this host.'];
    out.push(table(['#', 'Rule'], rules.map((r, i) => [String(i + 1), esc(r)])));
    return out.join('');
  } },
];
