// Headless verification of the handbook page served exactly as GitHub Pages serves it: the original shell and
// application run, the news template renders the handbook record, every chapter anchor exists, specimens render with
// their own stylesheets, hover parity with the live measurements, the phone tree renders the same record, every code
// excerpt resolved, no missing files on this host. Writes verification/report.json and screenshots.
import http from 'node:http';
import { readFileSync, writeFileSync, existsSync, statSync, createReadStream, mkdirSync } from 'node:fs';
import { join, extname, resolve } from 'node:path';
import { chromium } from 'playwright';
const root = resolve(new URL('..', import.meta.url).pathname); mkdirSync(join(root, 'verification'), { recursive: true });
const PORT = 8798;
const types = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.png': 'image/png', '.jpg': 'image/jpeg', '.svg': 'image/svg+xml', '.woff2': 'font/woff2', '.woff': 'font/woff', '.ttf': 'font/ttf', '.otf': 'font/otf', '.mp4': 'video/mp4', '.mp3': 'audio/mpeg', '.txt': 'text/plain', '.ico': 'image/x-icon', '.webp': 'image/webp', '.pdf': 'application/pdf', '.md': 'text/markdown' };
const server = http.createServer((req, res) => { let path = decodeURIComponent(new URL(req.url, 'http://x').pathname); let file = join(root, path); if (existsSync(file) && statSync(file).isDirectory()) file = join(file, 'index.html'); if (!file.startsWith(root) || !existsSync(file) || !statSync(file).isFile()) { if (!/\.[a-z0-9]+$/i.test(path) && existsSync(join(root, '404.html'))) { res.writeHead(404, { 'Content-Type': 'text/html; charset=utf-8' }); return createReadStream(join(root, '404.html')).pipe(res); } res.writeHead(404); return res.end('not found'); } res.writeHead(200, { 'Content-Type': types[extname(file).toLowerCase()] || 'application/octet-stream' }); createReadStream(file).pipe(res); }).listen(PORT, '127.0.0.1');
const results = []; const check = (name, ok, detail) => { results.push({ name, ok: !!ok, detail }); console.log((ok ? 'PASS ' : 'FAIL ') + name + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)).slice(0, 300) : '')); };
const DESKTOP_UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36';
const MOBILE_UA = 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1';
const browser = await chromium.launch(); const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, userAgent: DESKTOP_UA, locale: 'zh-CN' }); const page = await ctx.newPage();
const reqs = []; page.on('request', r => reqs.push(r.url())); const failed = []; const errors = []; page.on('response', r => { if (r.status() >= 400 && r.url().includes('127.0.0.1')) failed.push(r.status() + ' ' + r.url()); }); page.on('pageerror', e => errors.push(String(e.message).slice(0, 160)));
const loaderGone = async pg => { for (let i = 0; i < 60; i++) { await pg.waitForTimeout(500); if (await pg.$('.news-detail__content')) return true; } return false; };
const content = JSON.parse(readFileSync(join(root, 'handbook/handbook-content.json'), 'utf8')).data;
const coverage = JSON.parse(readFileSync(join(root, 'handbook/coverage.json'), 'utf8'));
const hover = JSON.parse(readFileSync(join(root, 'analysis/hover-states.json'), 'utf8'));
try {
  const t0 = Date.now(); await page.goto(`http://127.0.0.1:${PORT}/zh-cn/news/7013/`, { waitUntil: 'domcontentloaded', timeout: 90000 }); const gone = await loaderGone(page); await page.waitForLoadState('networkidle', { timeout: 20000 }).catch(() => { }); await page.waitForTimeout(2000);
  const shellFile = readFileSync(join(root, 'zh-cn/news/7013/index.html'), 'utf8'); const headScripts = [...shellFile.slice(0, shellFile.indexOf('</head>')).matchAll(/<script[^>]*src="([^"]+)"/g)].map(m => m[1]);
  check('shell untouched: the original scripts and the mirror adapter are the only head scripts in the served file', headScripts.every(src => /^\/_nuxt\/|^\/mirror\/|^\/archive\/files\/|hoyoverse\.com/.test(src)) && headScripts.some(src => src === '/mirror/adapter.js'), headScripts);
  check('news template rendered the handbook record', gone && (await page.$eval('.news-detail__title', e => e.textContent.trim())) === content.sTitle, { ms: Date.now() - t0 });
  const h4s = await page.$$eval('.news-detail__content h4[id]', es => es.map(e => e.id));
  check('every chapter anchor is in the rendered DOM', coverage.chapters.every(s => h4s.includes(s)) && h4s.includes('contents'), { chapters: coverage.chapters.length, found: h4s.length, missing: coverage.chapters.filter(s => !h4s.includes(s)).slice(0, 5) });
  check('rendered content matches the record (same number of headings, tables and images)', await page.evaluate(() => ({ h4: document.querySelectorAll('.news-detail__content h4').length, table: document.querySelectorAll('.news-detail__content table').length })).then(r => r.h4 === (content.sContent.match(/<h4/g) || []).length && r.table === (content.sContent.match(/<table/g) || []).length), await page.evaluate(() => ({ h4: document.querySelectorAll('.news-detail__content h4').length, table: document.querySelectorAll('.news-detail__content table').length })));
  check('no build errors or unresolved excerpts in the content', !/BUILD ERROR|excerpt anchor not found|excerpt unavailable/.test(content.sContent), (content.sContent.match(/BUILD ERROR[^<]{0,80}|excerpt anchor not found[^<]{0,80}/g) || []).slice(0, 4));
  const embedded = Object.keys(coverage.embedded); const sized = await page.evaluate(blocks => blocks.map(b => { const el = document.querySelector(`.news-detail__content [class~="${b}"], .news-detail__content [class^="${b}__"], .news-detail__content [class*=" ${b}__"]`); if (!el) return [b, null]; const r = el.getBoundingClientRect(); return [b, Math.round(r.width) + '×' + Math.round(r.height)]; }), embedded);
  check('embedded specimens render with non-zero size', sized.filter(([, s]) => s && s !== '0×0').length >= Math.min(embedded.length, 20) * 0.7, { embedded: embedded.length, nonZero: sized.filter(([, s]) => s && s !== '0×0').length, zero: sized.filter(([, s]) => !s || s === '0×0').map(x => x[0]).slice(0, 8) });
  const specIndex = JSON.parse(readFileSync(join(root, 'handbook/specimen-index.json'), 'utf8'));
  const cells = await page.evaluate(index => index.map(s => { const td = document.getElementById(s.id); if (!td) return { key: s.key, missing: true }; const r = td.getBoundingClientRect(); const stageTd = td.querySelector('td[style*="transform"]'); const rootEl = (stageTd || td).firstElementChild; const cs = rootEl ? getComputedStyle(rootEl) : null; const rr = rootEl ? rootEl.getBoundingClientRect() : null; return { key: s.key, w: Math.round(r.width), h: Math.round(r.height), hidden: cs ? cs.display === 'none' : true, position: cs && cs.position, inside: rr && stageTd ? (rr.right > r.left + 2 && rr.bottom > r.top + 2 && rr.left < r.right - 2 && rr.top < r.bottom - 2) : null, scroll: td.scrollWidth > td.clientWidth + 1 }; }), specIndex);
  const column = await page.$eval('.news-detail__content', e => Math.round(e.getBoundingClientRect().width));
  const badCells = cells.filter(c => c.missing || (!c.hidden && (c.h < 8 || c.w > column + 2 || c.inside === false)));
  check('every specimen cell renders inside the article column (at least 8 px high, not wider than the column, positioned roots inside their window)', cells.length > 20 && badCells.length === 0, { cells: cells.length, column, bad: badCells.slice(0, 6), hidden: cells.filter(c => c.hidden).map(c => c.key), staged: cells.filter(c => c.inside !== null).length, scrolling: cells.filter(c => c.scroll).map(c => c.key) });
  check('no horizontal overflow: the document is not wider than the viewport', await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, innerWidth: window.innerWidth })));
  const specimenImgs = await page.evaluate(() => [...document.querySelectorAll('td[id^="specimen-"] img[src]')].filter(i => i.getAttribute('src') && i.closest('td[id^="specimen-"]').getBoundingClientRect().height > 8).map(i => ({ src: (i.getAttribute('src') || '').slice(0, 100), lazy: i.hasAttribute('data-src'), broken: i.complete && i.naturalWidth === 0 && !/^data:/.test(i.getAttribute('src') || ''), opacity: getComputedStyle(i).opacity })));
  const badImgs = specimenImgs.filter(i => i.broken || (i.lazy && +i.opacity === 0));
  check('every specimen image loads, and lazy-loaded images are visible', specimenImgs.length > 20 && badImgs.length === 0, { images: specimenImgs.length, lazy: specimenImgs.filter(i => i.lazy).length, bad: badImgs.slice(0, 5) });
  check('extra original stylesheets are present in the head', (await page.$$eval('head style[data-original-stylesheet]', es => es.length)) > 20, { styles: await page.$$eval('head style[data-original-stylesheet]', es => es.length) });
  // hover parity: embedded specimens with a live hover diff must change the same computed property the same way
  const parity = []; for (const hh of hover.filter(x => x.cls && !/^(swiper-slide-active|reverse|light)$/.test(x.cls)).slice(0, 12)) { const el = await page.$(`.news-detail__content .${hh.cls.replace(/([^A-Za-z0-9_-])/g, '\\$1')}`); if (!el) continue; const bb = await el.boundingBox(); if (!bb || bb.width < 2) continue; const change = hh.changes.find(ch => ch.node.split('#')[1] === '0') || hh.changes[0]; const prop = Object.keys(change.props)[0]; await el.scrollIntoViewIfNeeded().catch(() => { }); await page.waitForTimeout(300); const bb2 = await el.boundingBox(); const before = await el.evaluate((e, prop) => getComputedStyle(e).getPropertyValue(prop), prop); await page.mouse.move(bb2.x + bb2.width / 2, bb2.y + Math.min(bb2.height / 2, 20)); await page.waitForTimeout(700); const after = await el.evaluate((e, prop) => getComputedStyle(e).getPropertyValue(prop), prop); await page.mouse.move(5, 5); await page.waitForTimeout(300); parity.push({ cls: hh.cls, prop, before, after, live: change.props[prop], match: after !== before && after === change.props[prop].after }); }
  check('hover parity: embedded specimens change the same computed property as the live measurement', parity.length > 0 && parity.filter(x => x.match).length >= Math.min(2, parity.length), parity.map(x => `${x.cls}.${x.prop}: ${x.match ? 'match' : x.before === x.after ? 'no change' : 'differs'}`));
  check('the links to the mirror routes are in the handbook', (await page.$$eval('.news-detail__content a', es => es.filter(a => /\/zh-cn\/main$/.test(a.getAttribute('href') || '')).length)) > 0, await page.$$eval('.news-detail__content a', es => ({ links: es.length, sample: es.slice(0, 3).map(a => a.getAttribute('href')) })));
  await page.screenshot({ path: join(root, 'verification/handbook-top-1440.png') }); await page.evaluate(() => document.getElementById('home-kv') && document.getElementById('home-kv').scrollIntoView()); await page.waitForTimeout(800); await page.screenshot({ path: join(root, 'verification/handbook-home-kv.png') });
  await page.evaluate(() => document.getElementById('coverage') && document.getElementById('coverage').scrollIntoView()); await page.waitForTimeout(800); await page.screenshot({ path: join(root, 'verification/handbook-coverage.png') });
  check('no JavaScript errors from the site code', errors.filter(e => !/GSAP target|ResizeObserver/.test(e)).length === 0, errors.slice(0, 4));
  const localFailed = failed.filter(f => !/favicon|\.ico|\/api\/|\/event\/|cdn-cgi/.test(f)); check('no missing files on this host', localFailed.length === 0, localFailed.slice(0, 6));
  const liveCdn = reqs.filter(u => /^https:\/\/(fastcdn|webstatic|act-webstatic)\.hoyoverse\.com\//.test(u) || /^https:\/\/zenless\.hoyoverse\.com\//.test(u)); check('nothing fetched from the live CDN or the live site (specimen images come from the archive)', liveCdn.length === 0, { live: liveCdn.length, sample: liveCdn.slice(0, 4).map(u => u.slice(0, 110)) });
  // phone tree renders the same record
  const mctx = await browser.newContext({ viewport: { width: 390, height: 844 }, userAgent: MOBILE_UA, isMobile: true, hasTouch: true, deviceScaleFactor: 2, locale: 'zh-CN' }); const mp = await mctx.newPage(); await mp.goto(`http://127.0.0.1:${PORT}/m/zh-cn/news/7013/`, { waitUntil: 'domcontentloaded', timeout: 90000 }); for (let i = 0; i < 60; i++) { await mp.waitForTimeout(500); if (await mp.$('.m-news-detail')) break; } await mp.waitForTimeout(2500);
  check('phone tree /m/zh-cn/news/7013 renders the handbook in the mobile news template', !!(await mp.$('.m-news-detail')) && (await mp.evaluate(() => document.body.innerText.includes('technical handbook'))), { url: mp.url() });
  await mp.screenshot({ path: join(root, 'verification/handbook-mobile-390.png') }); await mctx.close();
} catch (e) { check('verification run completed', false, String(e).slice(0, 400)); }
await browser.close(); server.close();
writeFileSync(join(root, 'verification/report.json'), JSON.stringify({ at: new Date().toISOString(), results }, null, 1));
console.log(`\n${results.filter(r => r.ok).length} passed, ${results.filter(r => !r.ok).length} failed`);
